#ifndef EAC_CAMPAIGN_BUILDER
#define EAC_CAMPAIGN_BUILDER


#include "EAC_CampaignNodes.h"
#include "EAC_RegionsInfo.h"


#include <vector>
#include <string>


// интерфейс "Каркас рассылки", используется для реализации различных каркасов рассылок
// вынесен в интерфейс, а не в постоянную сущность для гибкости при изменении требований 
// к внешнему виду рассылки заказчиками
struct ICampaignBuilder
{
    virtual std::string BuildCampaignHTML() = 0;
    virtual void AddNode(std::unique_ptr<ICampaignNode>&& node) = 0;

    virtual ~ICampaignBuilder() = default;
};


// класс "Базовый скелет", реализующий интерфейс каркаса рассылки, актуальный на 02.07.2026
class BaseCampaignBuilder final : public ICampaignBuilder
{
public:
    BaseCampaignBuilder() = default;
    BaseCampaignBuilder(const std::string& region) // передавать argv[2]
    {
        m_regionInfoFactory.ParseRegion(region);
        m_regionInfo = m_regionInfoFactory.CreateRegionInfo();
    }

    std::string BuildCampaignHTML() override
    {
        std::string rawHTML{};
        rawHTML += BuildHeader();
        
        std::vector<std::unique_ptr<ICampaignNode>> processedNodes{};
        InsertSpacingNodes(processedNodes);
        AdjustLastParagraphSpacing(processedNodes);

        for (auto& campaignNode : processedNodes)
        {
            rawHTML += campaignNode->GetHTMLRepresentation();
        }

        rawHTML += BuildFooter();
        return rawHTML;
    }

    void AddNode(std::unique_ptr<ICampaignNode>&& node) override
    {
        m_campaignNodes.push_back(std::move(node));
    }

private:
    std::string BuildHeader()
    {
        std::string rawHTML{};
        rawHTML += std::string(R"(
                        <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
                        <html lang="en"><!-- GENERATED BY EAC_COMPILER v1.0, 08.07.2026 -->

                        <head>
                            <title>iSpring</title>
                            <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
                            <meta name="viewport" content="width=device-width, initial-scale=1.0">

                            <!--[if !mso]><!-->
                            <meta http-equiv="X-UA-Compatible" content="IE=edge">
                            <!--<![endif]-->
                            <!--[if mso]><noscript>
                                 <xml>
                                   <o:OfficeDocumentSettings>
                                   <o:AllowPNG></o:AllowPNG>
                                   <o:PixelsPerInch>96</o:PixelsPerInch>
                                   </o:OfficeDocumentSettings>
                                 </xml>
                              </noscript><![endif]-->

                            <style type="text/css">
                                html {
                                    -webkit-text-size-adjust: none;
                                    -ms-text-size-adjust: none;
                                }

                                #outlook a {
                                    padding: 0;
                                }

                                table {
                                    mso-table-lspace: 0pt;
                                    mso-table-rspace: 0pt;
                                }

                                img {
                                    -ms-interpolation-mode: bicubic;
                                }

                                @media screen and (min-width: 1600px) {

                                    td[class="table"] th,
                                    td[class="x_table"] th,
                                    td[class="table"] td,
                                    td[class="x_table"] td {
                                        padding: 10px !important;
                                        font-size: 16px !important;
                                        line-height: 24px !important;
                                    }

                                    td[class="table"] th *,
                                    td[class="x_table"] th *,
                                    td[class="table"] td *,
                                    td[class="x_table"] td * {
                                        font-size: 16px !important;
                                        line-height: 24px !important;
                                    }

                                    div[class="two-columns__left"],
                                    div[class="x_two-columns__left"] {
                                        max-width: 270px !important;
                                        float: left;
                                    }

                                    div[class="two-columns__right"],
                                    div[class="x_two-columns__right"] {
                                        max-width: 290px !important;
                                        float: right;
                                    }

                                    td[class="two-columns__bordered"],
                                    td[class="x_two-columns__bordered"] {
                                        border-left: 1px solid #dcdcdf;
                                        padding-left: 19px;
                                    }
                                }
                            </style>

                            <!--[if mso]><xml>
                            <w:WordDocument xmlns:w="urn:schemas-microsoft-com:office:word">
                              <w:DontUseAdvancedTypographyReadingMail/>
                            </w:WordDocument>
                            </xml><![endif]-->

                            <!--[if !mso]><!-- -->
                            <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,700,700i" rel="stylesheet">
                            <!--<![endif]-->

                        </head>

                        <body style="padding-top: 0; padding-right: 0; padding-bottom: 0; padding-left: 0; 
                        margin-top: 0; margin-right: 0; margin-bottom: 0; margin-left: 0;">
                            <table style="border-collapse: collapse; table-layout: fixed; -webkit-text-size-adjust: 100%; 
                            -ms-text-size-adjust: 100%; background-color: #ffffff; color: #3d3e47; font-size: 16px; 
                            line-height: 24px; font-family: Roboto, Helvetica, sans-serif; cursor: default;" border="0" 
                            width="100%" cellspacing="0" cellpadding="0" bgcolor="#ffffff">
                                <!--START: Preheader-->
                                <tbody>
                                    <tr>
                                        <td style="background-color: #e4e7ea;" align="center" bgcolor="#ffffff;">

                                            <!-- [if (gte mso 9)|(IE)]><table width="600" border="0" cellpadding="0" cellspacing="0" 
                                            style="margin-right: auto; margin-left: auto;"><tr><td align="center"><![endif]-->

                                            <div style="width: 100%; max-width: 600px; min-width: 320px; margin-right: auto; margin-left: auto;">
                                                <table style="max-width: 600px; min-width: 320px; margin-right: auto; margin-left: auto;" 
                                                border="0" width="100%" cellspacing="0" cellpadding="0">
                                                    <tbody>
                                                        <tr style="background-color: #ffffff;">
                                                            <td width="15" class="esd-text"><br></td>
                                                            <td align="left">
                                                                <table border="0" width="100%" cellspacing="0" cellpadding="0">
                                                                    <tbody>
                                                                        <tr>
                                                                            <td style="font-size: 0; line-height: 30px;" height="30" class="esd-text">
                                                                                &nbsp;
                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td align="left">
                                                                                <a href=")" + m_regionInfo->GetHeaderLink() + R"(" target="_blank">
                                                                                    <img src="https://content.app-us1.com/a5EQL/2025/04/02/07eafe75-a42b-4345-b365-b6c30fb4db69.png" 
                                                                                    border="0" alt="iSpring" width="126" height="31" style="display: block; color: #151824; 
                                                                                    font-weight: bold; font-size: 16px; line-height: 30px; 
                                                                                    font-family: Roboto, Helvetica, sans-serif; text-decoration: underline;">
                                                                                </a>
                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td style="font-size: 0px; line-height: 30px; height: 30px;" class="esd-text">
                                                                                &nbsp;
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table>
                                                            </td>
                                                            <td width="15" class="esd-text"><br></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                            
                                            <!-- [if (gte mso 9)|(IE)]></td></tr></table><![endif]-->

                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="background-color: #e4e7ea;" align="center" bgcolor="#ffffff;">

                                            <!-- [if (gte mso 9)|(IE)]><table width="600" border="0" cellpadding="0" cellspacing="0" 
                                            style="margin-right: auto; margin-left: auto;"><tr><td align="center"><![endif]-->
                                            
                                            <div style="width: 100%; max-width: 600px; min-width: 320px; margin-right: auto; margin-left: auto;">
                                                <table style="max-width: 600px; min-width: 320px; margin-right: auto; margin-left: auto;" 
                                                border="0" width="100%" cellspacing="0" cellpadding="0">
                                                    <tbody>
                                                        <tr style="background-color: #ffffff;">
                                                            <td width="15" class="esd-text"><br></td>
                                                            <td align="center">
                                                                <table border="0" width="100%" cellspacing="0" cellpadding="0">
                                                                    <tbody>)");
        return rawHTML;
    }

    std::string BuildFooter()
    {
        std::string rawHTML{};
        rawHTML += std::string(R"(          </tbody>
                                        </table>
                                    </td>
                                    <td width="15" class="esd-text">
                                        <br>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <!-- [if (gte mso 9)|(IE)]></td></tr></table><![endif]-->

                </td>
            </tr>
            <tr>
                <td style="background-color: #e4e7ea;" align="center" bgcolor="#ffffff;">

                    <!-- [if (gte mso 9)|(IE)]><table width="600" border="0" cellpadding="0" cellspacing="0" 
                    style="margin-right: auto; margin-left: auto;"><tr><td align="center"><![endif]-->

                    <div style="width: 100%; max-width: 600px; min-width: 320px; margin-right: auto; margin-left: auto;">
                        <table style="max-width: 600px; min-width: 320px; margin-right: auto; margin-left: auto;" 
                        border="0" width="100%" cellspacing="0" cellpadding="0">
                            <tbody>
                                <tr style="background-color: #ffffff;">
                                    <td width="15" class="esd-text">
                                        <br>
                                    </td>
                                    <td align="center">
                                        <table border="0" width="100%" cellspacing="0" cellpadding="0">
                                            <tbody>
                                                <tr>
                                                    <td style="font-size: 0; line-height: 50px;" height="50" class="esd-text">
                                                        &nbsp;
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="background-color: #dcdcdf; font-size: 0; line-height: 1px;" 
                                                    bgcolor="#dcdcdf" height="1" class="esd-text">
                                                        &nbsp;
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="font-size: 0; line-height: 50px;" height="50" class="esd-text">
                                                        &nbsp;
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                    <td width="15" class="esd-text">
                                        <br>
                                    </td>
                                </tr>
                                <tr style="background-color: #ffffff;">
                                    <td colspan="3" align="center">
                                        <table border="0" width="100%" cellspacing="0" cellpadding="0">
                                            <tbody>
                                                <tr>
                                                    <td align="center">
                                                        <table border="0" width="225" cellspacing="0" cellpadding="0">
                                                            <tbody>
                                                                <tr>
                                                                    <td width="37">
                                                                        <a title="Facebook" href=")" + m_regionInfo->GetFacebookLink() + R"(" target="_blank"><img src="https://content.app-us1.com/a5EQL/2025/03/27/7fa849ac-a0da-4525-9587-36ee52b01f35.png" border="0" alt="Facebook" width="37" height="37" style="display: block; width: 37px; height: 37px; color: #1b72f3; font-weight: 400; font-size: 10px; line-height: 36px; font-family: Roboto, Helvetica, sans-serif; text-align: center; text-decoration: underline;"></a></td>
                                                                    <td width="10" class="esd-text">&nbsp;</td>
                                                                    <td width="37">
                                                                        <a title="X" href=")" + m_regionInfo->GetXLink() + R"(" target="_blank"><img src="https://content.app-us1.com/a5EQL/2025/03/27/e22021d4-90bd-4587-8e5d-cf31bfb1fbe4.png" border="0" alt="X" width="37" height="37" style="display: block; width: 37px; height: 37px; color: #1b72f3; font-weight: 400; font-size: 10px; line-height: 36px; font-family: Roboto, Helvetica, sans-serif; text-align: center; text-decoration: underline;"></a></td>
                                                                    <td width="10" class="esd-text">&nbsp;</td>
                                                                    <td width="37">
                                                                        <a title="linkedIn" href=")" + m_regionInfo->GetLinkedInLink() + R"(" target="_blank"><img src="https://content.app-us1.com/a5EQL/2025/03/27/60e922b5-7499-40e4-bf28-358cbbfab0b9.png" border="0" alt="linkedIn" width="37" height="37" style="display: block; width: 37px; height: 37px; color: #1b72f3; font-weight: 400; font-size: 10px; line-height: 36px; font-family: Roboto, Helvetica, sans-serif; text-align: center; text-decoration: underline;"></a></td>
                                                                    <td width="10" class="esd-text">&nbsp;</td>
                                                                    <td width="37">
                                                                        <a title="YouTube" href=")" + m_regionInfo->GetYouTubeLink() + R"(" target="_blank"><img src="https://content.app-us1.com/a5EQL/2025/03/27/ed8b7e5f-534a-4427-be8b-32f23a2ea8b4.png" border="0" alt="YouTube" width="37" height="37" style="display: block; width: 37px; height: 37px; color: #1b72f3; font-weight: 400; font-size: 10px; line-height: 36px; font-family: Roboto, Helvetica, sans-serif; text-align: center; text-decoration: underline;"></a></td>
                                                                    <td width="10" class="esd-text">&nbsp;</td>
                                                                    <td width="37">
                                                                        <a title="Instagram" href=")" + m_regionInfo->GetInstagramLink() + R"(" target="_blank"><img src="https://content.app-us1.com/a5EQL/2025/03/27/f052d95e-576a-46c2-ad08-fea14fe75f83.png" border="0" alt="Instagram" width="37" height="37" style="display: block; width: 37px; height: 37px; color: #1b72f3; font-weight: 400; font-size: 10px; line-height: 36px; font-family: Roboto, Helvetica, sans-serif; text-align: center; text-decoration: underline;"></a></td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </td>
                                                </tr>

                                                <tr>
                                                    <td style="font-size: 0; line-height: 30px;" height="30" class="esd-text">
                                                        &nbsp;
                                                    </td>
                                                </tr>

                                                <tr>
                                                    <td style="color: #3d3e47; font-weight: 400; font-size: 14px; line-height: 24px; 
                                                    font-family: Roboto, Helvetica, sans-serif; text-align: center;" align="center" 
                                                    class="esd-text">
                                                        <span style="color: #3d3e47; font-weight: 400; font-size: 14px; line-height: 24px; 
                                                        font-family: Roboto, Helvetica, sans-serif; text-align: center;">
                                                            © 2001-%FOOTER_CURRENT_YEAR% iSpring Solutions, Inc.
                                                        </span>
                                                    </td>
                                                </tr>

                                                <tr>
                                                    <td style="color: #3d3e47; font-weight: 400; font-size: 14px; line-height: 24px; 
                                                    font-family: Roboto, Helvetica, sans-serif; text-align: center;" align="center" 
                                                    class="esd-text">
                                                        <span style="color: #3d3e47; font-weight: 400; font-size: 14px; line-height: 24px; 
                                                        font-family: Roboto, Helvetica, sans-serif; text-align: center;">
                                                            %SENDER-INFO-SINGLELINE%
                                                        </span>
                                                    </td>
                                                </tr>

                                                <tr>
                                                    <td style="color: #3d3e47; font-weight: 400; font-size: 14px; line-height: 24px; 
                                                    font-family: Roboto, Helvetica, sans-serif; text-align: center;" align="center" 
                                                    class="esd-text">
                                                        <a style="color: #3d3e47; font-weight: 400; font-size: 14px; line-height: 24px; 
                                                        font-family: Roboto, Helvetica, sans-serif; text-align: center; text-decoration: underline;" 
                                                        href=")" + m_regionInfo->GetAboutiSpringLink() + R"(" target="_blank">
                                                            )" + m_regionInfo->GetAboutiSpringText() + R"(
                                                        </a> &nbsp;&nbsp;|&nbsp;&nbsp; 

                                                        <a style="color: #3d3e47; font-weight: 400; font-size: 14px; line-height: 24px; 
                                                        font-family: Roboto, Helvetica, sans-serif; text-align: center; text-decoration: underline;" 
                                                        href="%UNSUBSCRIBELINK%" target="_blank">
                                                            )" + m_regionInfo->GetUnsubscribeText() + R"(
                                                        </a> &nbsp;&nbsp;|&nbsp;&nbsp; 

                                                        <a style="color: #3d3e47; font-weight: 400; font-size: 14px; line-height: 24px; 
                                                        font-family: Roboto, Helvetica, sans-serif; text-align: center; text-decoration: underline;" 
                                                        href=")" + m_regionInfo->GetPrivacyPolicyLink() + R"(" target="_blank">
                                                            )" + m_regionInfo->GetPrivacyPolicyText() + R"(
                                                        </a>
                                                    </td>
                                                </tr>

                                                <tr>
                                                    <td style="font-size: 0; line-height: 50px;" height="50" class="esd-text">
                                                        &nbsp;
                                                    </td>
                                                </tr>

                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                    </div><!-- [if (gte mso 9)|(IE)]></td></tr></table><![endif]-->
               
                </td>
            </tr>
        </tbody>
    </table>
</body><!-- GENERATED BY EAC_COMPILER v1.0, 08.07.2026 -->

</html>)");

        return rawHTML;
    }

    std::vector<std::unique_ptr<ICampaignNode>> m_campaignNodes{};
    RegionInfoFactory m_regionInfoFactory{};
    std::unique_ptr<IRegionInfo> m_regionInfo{};

    static constexpr unsigned int SPACE_BETWEEN_PARAGRAPHS = 20;
    static constexpr unsigned int SPACE_ABOVE_BELOW_BUTTON = 35;
    static constexpr unsigned int SPACE_BETWEEN_PRE_LAST = 60;
    static constexpr unsigned int SPACE_ABOVE_SENDER = 10;
    static constexpr unsigned int SPACE_ZERO = 0;
    static constexpr unsigned int SPACE_BEFORE_LIST = 10;

    void InsertSpacingNodes(std::vector<std::unique_ptr<ICampaignNode>>& processedNodes)
    {
        if (m_campaignNodes.empty())
        {
            return;
        }

        std::vector<NodeType> nodeTypes{};
        for (const auto& campaignNode : m_campaignNodes)
        {
            nodeTypes.push_back(campaignNode->GetNodeType());
        }

        for (size_t k = 0; k < m_campaignNodes.size(); ++k)
        {
            processedNodes.push_back(std::move(m_campaignNodes[k]));
            if (k == m_campaignNodes.size() - 1)
            {
                break;
            }

            NodeType currentNodeType = nodeTypes[k];
            NodeType nextNodeType = nodeTypes[k + 1];

            unsigned int spacingNodeHeight = GetSpacingHeightBySemantic(currentNodeType, nextNodeType, k, nodeTypes);
            if (spacingNodeHeight > 0)
            {
                processedNodes.push_back(std::make_unique<SpacingNode>(spacingNodeHeight));
            }
        }
    }

    unsigned int GetSpacingHeightBySemantic(NodeType curr, NodeType next, size_t idx, const std::vector<NodeType>& nodeTypes)
    {
        bool isNextLastReal = true;
        for (size_t k = idx + 1; k < nodeTypes.size(); ++k)
        {
            if (nodeTypes[k] != NodeType::SENDER_NODE && nodeTypes[k] != NodeType::SPACING_NODE)
            {
                isNextLastReal = false;
                break;
            }
        }

        if (next == NodeType::BUTTON_NODE || next == NodeType::BUTTONS_ROW_NODE)
        {
            if (isNextLastReal)
                return SPACE_BETWEEN_PRE_LAST;
            else
                return SPACE_ABOVE_BELOW_BUTTON;
        }

        if ((curr == NodeType::BUTTON_NODE || curr == NodeType::BUTTONS_ROW_NODE) && next == NodeType::PARAGRAPH_NODE)
        {
            if (isNextLastReal)
                return SPACE_BETWEEN_PRE_LAST;
            else
                return SPACE_ABOVE_BELOW_BUTTON;
        }

        if (next == NodeType::PARAGRAPH_NODE && isNextLastReal)
        {
            return SPACE_BETWEEN_PRE_LAST;
        }

        if (curr == NodeType::PARAGRAPH_NODE && next == NodeType::PARAGRAPH_NODE)
        {
            return SPACE_BETWEEN_PARAGRAPHS;
        }

        if (next == NodeType::SENDER_NODE)
        {
            return SPACE_ABOVE_SENDER;
        }

        if (curr == NodeType::SENDER_NODE)
        {
            return SPACE_ZERO;
        }

        if (next == NodeType::LABELED_LIST_NODE || next == NodeType::DOT_LIST_NODE)
        {
            return SPACE_BEFORE_LIST;
        }

        return SPACE_BETWEEN_PARAGRAPHS;
    }

    void AdjustLastParagraphSpacing(std::vector<std::unique_ptr<ICampaignNode>>& nodes)
    {
        if (nodes.empty()) 
        {
            return;
        }

        int lastParagraphIdx = -1;
        for (int i = static_cast<int>(nodes.size()) - 1; i >= 0; --i)
        {
            if (nodes[i]->GetNodeType() == NodeType::PARAGRAPH_NODE)
            {
                lastParagraphIdx = i;
                break;
            }
        }

        if (lastParagraphIdx == -1) 
        {
            return;
        }

        if (lastParagraphIdx > 0)
        {
            auto& prevNode = nodes[lastParagraphIdx - 1];
            if (prevNode->GetNodeType() == NodeType::SPACING_NODE)
            {
                auto* spacing = dynamic_cast<SpacingNode*>(prevNode.get());
                if (spacing) spacing->SetSpacingHeight(SPACE_BETWEEN_PRE_LAST);
                return;
            }
        }

        auto spacing = std::make_unique<SpacingNode>(SPACE_BETWEEN_PRE_LAST);
        nodes.insert(nodes.begin() + lastParagraphIdx, std::move(spacing));
    }


};


#endif